### ISSUE TITLE
Extension rejected from Marketplace

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-easytabs#11]
Code Issues: Testing:  Errors were discovered during testing and will be listed in the  Additional Comments section below. Once these issues are corrected,  please reupload your package.
--
 
Additional Comments:                                                                                     Test environments used:    Magento 2.2.5 Open Source (PHP 7.1.21)  Magento 2.1.14 Community Edition (PHP 5.6.37)    Reasons for failure:    In Magento 2.1, delete mass action on Product Page Tabs grid causes a 500 error and generates the following PHP error:    [05-Sep-2018 21:21:54 UTC] PHP Fatal error:  Call to undefined method Swissup\Easytabs\Model\ResourceModel\Entity\Grid\ProductCollection::_getAllIdsSelect() in /var/www/html/vendor/swissup/easytabs/Model/ResourceModel/Entity/Grid/Collection.php on line 91    Mass action on Widget Tabs grids all redirect to a 404 page.

**Comment by roma84** [comment]
Fixed.
