### ISSUE TITLE
Load attribute content on configurable option change

### ISSUE THREAD

**Issue by bohdanchumak** [swissup/module-easytabs#18]
Dynamically update the content for simple products within a configurable product based on the currently selected values.

**Comment by gino2014** [comment]
Would be great feature. Maybe also for product details tab that include product attributes like color, size, and so on.
Any time line for that feature?

**Comment by gino2014** [comment]
Just an idea to proceed with this option is https://github.com/Beraa995/configurable-product-options
maybe you could cooperate with Beraa995.

**Comment by tangar76** [comment]
Thanks for the suggestion. Module from Beraa995 should works great with our tabs module. The only thing you have to disable ajax for tabs you want to update.
