### ISSUE TITLE
Product reviews are not loaded when expanded tabs layout used

### ISSUE THREAD

**Issue by roma84** [swissup/module-easytabs#20]
I have been trying your free tabs extension and I noticed that when I choose the "horizontal" tab style the reviews aren't loaded unless one clicks on "review" at the top of the page.
I assume that is because when one scrolls down it does not trigger the ajax load that reviews do.
see on my test site:
https://www.m2.alpinewines.co.uk/alpineshop/aigle-les-murailles-white-badoux.html

Swissup MZM-04502

**Comment by tangar76** [comment]
As a temporary solution you can enable option "Load content with ajax" for a tab.
