### ISSUE TITLE
when module is disabled and re enabled, attribute tabs break

### ISSUE THREAD

**Issue by iphigenie** [swissup/module-easytabs#21]
A tiny issue I noticed as I was testing.

Disabled and re enabled the module with module:enable.

Attribute tabs will cause the following error
Warning: Invalid argument supplied for foreach() in .../vendor/swissup/module-easytabs/view/frontend/templates/tab/catalog/product/attribute.phtml on line 1

All the configuration etc. survived fine but for the attribute codes list the data seems to get an extra escape on the array quotes

![attribute lost](https://user-images.githubusercontent.com/1055826/72352746-ba9f6480-36da-11ea-867b-03d7141e5432.jpg)

Re-selecting the attributes and saving settings for each attribute tab fixed it so it is not a big problem, just thought you'd like to know

**Comment by tangar76** [comment]
We can't reproduce this problem in our environment.
Attribute tab works as expected at backend and at frontend after enable module back.

**Comment by tangar76** [comment]
Closed due to inactivity.
