### ISSUE TITLE
floating/sticky tabs

### ISSUE THREAD

**Issue by tangar76** [swissup/module-easytabs#3]
add possibility to replace tabs with some other output that will display whole content.

**Comment by dimdimich** [comment]
Can we add option to use same floating and explanded tabs style we have for https://beavertools.com/28900-wilton-cold-front-3037-atomized-cooling-fan-wacf-3037.html

**Comment by rommmka** [comment]
Please check following example:

https://www.leatherology.com/aleena-soft-zippered-tote-red-leather-bordeaux/
