### ISSUE TITLE
Have reviews tab automatically open

### ISSUE THREAD

**Issue by bohdanchumak** [swissup/module-easytabs#34]
The issue can be reproduced on Argento Stripes with Expanded Tabs. When opening a product page with reviews, the tabs show the review form but don't show existing reviews unless you click on the tab.

WKD-11375

**Comment by tangar76** [comment]
Can you please provide p[age with this issue.
Locally everything works great for me.

**Comment by tangar76** [comment]
Issue occurs when tabs layout is expanded and reviews tab has enabled option "Load content with ajax"
