### ISSUE TITLE
a CMS block in the "Review Form Fields Before"

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-easytabs#8]
Hi, just a quick bug report. Don't need support, just add it to your list. Easytabs 1.3.0 If I add a widget to display a CMS block in the "Review Form Fields Before" container it works using Magento tabs, but does not appear on the Review tab created by Easytabs.

Best wishes

Graham

**Comment by tangar76** [comment]
Unfortunately it is not possible with Easytabs module.
Solution is to create custom template of override template `Magento_Review::review.phtml` in your custom theme.
